### ISSUE TITLE
Check these issues out

### ISSUE THREAD

**Issue by Harshpreet-hostinko** [Hostinko/hostinko-cs#1]
Pls , direct home and contact us links of whmcs nav bar to the main pages guys !!

**Comment by animeshsinghweb** [comment]
@Harshpreet-hostinko, please post issues related to Hostinko Official 2016 edition at the repo Off16 repo.
https://github.com/Hostinko/Off16/issues 
Also try using images wherever possible for clear observation of the issues.
Thanks.
